# -*- coding: utf-8 -*-
"""Tourism_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTpqJP6UctJAJN9f4NSRrRSvYy_BRUo1

# **Project Name**    -   Tourism Experience Analytics: Classification, Prediction, and Recommendation System

##### **Project Type**    - EDA/Regression/Classification/Unsupervised
##### **Contribution**    - Individual

# **Project Summary -**

This project focuses on analyzing and predicting tourism-related patterns using Machine Learning and Data Analytics techniques. The main objective of the project was to understand tourist behavior, attraction popularity, and user preferences to build an accurate tourism prediction and recommendation system.

The project began with data collection and preprocessing. Multiple datasets related to users, attractions, cities, countries, and tourism transactions were merged into a single dataframe for analysis. Data cleaning techniques were applied to handle missing values, remove duplicates, and treat outliers. Categorical variables were encoded into numerical form, and feature scaling techniques were used to prepare the data for machine learning models.

Exploratory Data Analysis (EDA) was performed using various visualizations such as count plots, bar charts, heatmaps, pair plots, and box plots. These visualizations helped identify important insights related to seasonal tourism trends, popular attraction types, tourist visit patterns, and rating distributions. Correlation analysis was also conducted to understand relationships among variables.

Feature engineering and feature selection techniques were used to improve model performance and reduce overfitting. Important features such as AttractionPopularity, AvgUserRating, VisitMonth, UserVisitCount, and AttractionTypeId were identified as major factors influencing tourist ratings and travel behavior.

**Several machine learning models were implemented, including:**

* Linear Regression
* Decision Tree Regressor
* Random Forest Regressor

Hyperparameter optimization using GridSearchCV was applied to improve model performance. The models were evaluated using regression metrics such as MAE, MSE, RMSE, and R² Score. Among all models, the optimized Random Forest Regressor achieved the best performance with the highest prediction accuracy and lowest error values.

The project also included a classification model for Visit Mode prediction and a recommendation system using collaborative filtering techniques to recommend attractions to users based on similarity analysis.

To improve model interpretability, feature importance analysis was performed using the Random Forest model. This helped identify the most influential features affecting prediction outcomes and provided valuable business insights for tourism planning and recommendation systems.

Finally, the best-performing model was saved using Joblib/Pickle format for deployment. A Streamlit web application was developed to allow users to input tourism-related data and receive prediction results interactively.

Overall, this project successfully demonstrated how Machine Learning can be used in tourism analytics to improve prediction accuracy, enhance customer recommendations, support business decision-making, and provide better tourism experiences.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**Tourism agencies and travel platforms aim to enhance user experiences by leveraging data to provide personalized recommendations, predict user satisfaction, and classify potential user behavior. This project involves analyzing user preferences, travel patterns, and attraction features to achieve three primary objectives: regression, classification, and recommendation.**

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 15 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]





6. You may add more ml algorithms for model creation. Make sure for each and every algorithm, the following format should be answered.


*   Explain the ML Model used and it's performance using Evaluation metric Score Chart.


*   Cross- Validation & Hyperparameter Tuning

*   Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

*   Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

!pip install streamlit

# Import Libraries

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# ML
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

# Metrics
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    accuracy_score,
    classification_report
)

# Recommendation
from sklearn.metrics.pairwise import cosine_similarity

# Streamlit
import streamlit as st

"""### Dataset Loading"""

# Load Dataset

transactions = pd.read_excel("Transaction.xlsx")
users = pd.read_excel("User.xlsx")
cities = pd.read_excel("City.xlsx")
types = pd.read_excel("Type.xlsx")
visit_modes = pd.read_excel("Mode.xlsx")
countries = pd.read_excel("Country.xlsx")
regions = pd.read_excel("Region.xlsx")
continents = pd.read_excel("Continent.xlsx")
items = pd.read_excel("Item.xlsx")

"""### Dataset First View"""

# Dataset First Look

transactions.head()

cities.head()

continents.head()

countries.head()

items.head()

visit_modes.head()

regions.head()

types.head()

users.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
cities.shape

continents.shape

countries.shape

items.shape

visit_modes.shape

regions.shape

transactions.shape

types.shape

users.shape

"""### Dataset Information"""

# Dataset Info

cities.info()

continents.info()

countries.info()

items.info()

visit_modes.info()

regions.info()

transactions.info()

types.info()

users.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
cities.duplicated().sum()

continents.duplicated().sum()

countries.duplicated().sum()

items.duplicated().sum()

visit_modes.duplicated().sum()

regions.duplicated().sum()

transactions.duplicated().sum()

types.duplicated().sum()

users.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
cities.isnull().sum()

continents.isnull().sum()

countries.isnull().sum()

items.isnull().sum()

visit_modes.isnull().sum()

regions.isnull().sum()

regions.isnull().sum()

transactions.isnull().sum()

types.isnull().sum()

users.isnull().sum()

# Visualizing the missing values
cities.isnull().sum().plot(kind="bar")

users.isnull().sum().plot(kind="bar")

"""### What did you know about your dataset?

The dataset is a structured tourism dataset containing information about users, attractions, ratings, visit modes, and locations. It includes tables like Transaction Data, User Data, Attraction Data, City, Country, Region, and Visit Mode Data.

**It is used for:**

* Regression: Predict attraction ratings
* Classification: Predict visit mode (Family, Business, Couples, etc.)
* Recommendation: Suggest tourist attractions to users

**The dataset contains:**

* User demographics
* Travel history
* Attraction details
* Ratings and preferences
* Geographic information

This dataset helps analyze tourism trends and build personalized recommendation systems.

## ***2. Understanding Your Variables***
"""

# Dataset Columns

cities.columns

continents.columns

countries.columns

items.columns

visit_modes.columns

regions.columns

transactions.columns

types.columns

users.columns

# Dataset Describe

cities.describe()

continents.describe()

countries.describe()

items.describe()

visit_modes.describe()

regions.describe()

transactions.describe()

types.describe()

users.describe()

"""### Variables Description

# **Variable**   =>  	**Description**

---




* TransactionId  ->	Unique ID for each transaction
* UserId  ->		Unique ID of the user
* VisitYear  ->	Year of attraction visit
* VisitMonth	  ->	Month of attraction visit
* VisitMode  ->		Type of travel (Business, Family, Couples, Friends, etc.)
* AttractionId  ->		Unique ID of tourist attraction
* Rating  ->		Rating given by user to attraction
* ContinentId  ->		Unique ID of continent
* RegionId	  ->	Unique ID of region
* CountryId	  ->	Unique ID of country
* CityId	  ->	Unique ID of city
* CityName  ->		Name of city
* AttractionTypeId	  ->	Unique ID of attraction category
* AttractionType  ->		Type of attraction (Beach, Museum, Park, etc.)
* VisitModeId  ->		Unique ID of visit mode
* Continent  ->		Name of continent
* Country  ->		Name of country
* Region  ->		Name of region
* AttractionCityId  ->		City where attraction is located
* Attraction  ->		Name of tourist attraction
* AttractionAddress  ->		Address of attraction

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.

cities.nunique()

continents.nunique()

countries.nunique()

items.nunique()

visit_modes.nunique()

regions.nunique()

transactions.nunique()

types.nunique()

users.nunique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# Remove Null Values

cities['CityId'].fillna(cities['CityId'].mode()[0], inplace=True)
users['CityId'].fillna(users['CityId'].mode()[0], inplace=True)

countries['CountryId'].drop_duplicates(inplace=True)

transactions['VisitYear'] = transactions['VisitYear'].astype(int)

# Merge all datasets into a single dataframe

df = transactions.merge(users, on='UserId', how='left')

df = df.merge(cities, on='CityId', how='left')


df = df.merge(regions, on='RegionId', how='left')


df = df.merge(items, on='AttractionId', how='left')

df = df.merge(types, on='AttractionTypeId', how='left')

df = df.merge(
    countries[['CountryId', 'Country']],
    left_on='CountryId_x',
    right_on='CountryId',
    how='left'
)


visit_count = df.groupby('UserId')['TransactionId'].count()

avg_rating = df.groupby('UserId')['Rating'].mean()

le = LabelEncoder()

df['VisitMode'] = le.fit_transform(df['VisitMode'])



def season(month):
    if month in [12,1,2]:
        return "Winter"

    elif month in [3,4,5]:
        return "Spring"

    elif month in [6,7,8]:
        return "Summer"

    elif month in [9,10,11]:
        return "Autumn"

df['Season'] = df['VisitMonth'].apply(season)

df = df.merge(
    continents[['ContinentId', 'Continent']],
    left_on='ContinentId_x',
    right_on='ContinentId',
    how='left'
)

df.head()

# Check shape
# df.shape

# Check null values
# df.isnull().sum()

"""### What all manipulations have you done and insights you found?

# **Manipulations Done**
* Handled missing values
* Removed duplicate records
* Corrected data types
* Merged datasets


* Encoded categorical variables


* Validated final dataset
# **Insights Found**
* Family and couples were common visit modes
* Some attractions received higher ratings consistently
* Certain regions had higher tourism activity
* Most users gave medium-to-high ratings
* Travel behavior varied by country and continent
* Popular attractions had repeated visits
* Seasonal tourism patterns were observed
* Final dataset became ready for EDA and ML models

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code

sns.countplot(x='Continent', data=df)

plt.xticks(rotation=90)
plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Count Plot because it is best suited for visualizing the frequency distribution of categorical variables like Continent. It helps compare the number of tourists from different continents clearly and makes the dataset easier to understand.

##### 2. What is/are the insight(s) found from the chart?

* Some continents have significantly higher tourist counts than others.
* The dataset shows uneven tourist distribution across regions.
* Certain continents contribute more users and tourism activity.
* It helps identify major target regions for tourism businesses.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights can create a positive business impact because:**

Tourism companies can focus marketing on high-tourist regions.
Businesses can provide personalized travel packages based on regional preferences.
It helps improve customer targeting and recommendation systems.
# **Negative Growth Insight**

**Yes, low tourist activity from some continents may indicate:**

* Poor marketing reach
* Less attraction popularity
* Limited tourism engagement in those regions

#### Chart - 2
"""

# Chart - 2 visualization code

sns.histplot(df['Rating'], bins=10, kde=True)

plt.title("Distribution of Ratings")
plt.xlabel("Ratings")
plt.ylabel("Count")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Histogram Plot because it is best for understanding the distribution of numerical data like ratings. It helps identify:

* Most common ratings
* Data spread
* Skewness
* User rating behavior

##### 2. What is/are the insight(s) found from the chart?

* Most users gave medium-to-high ratings.
* Very low ratings are less frequent.
* The rating distribution is concentrated around positive values.
* This indicates that many attractions provide satisfactory experiences.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights can positively impact the business because:**

* Highly rated attractions can be promoted more.
* Businesses can identify successful attraction categories.
* Positive user satisfaction improves customer retention.
# **Negative Growth Insight**

**If some attractions consistently receive low ratings, it may indicate:**

* Poor service quality
* Bad customer experience
* Lack of facilities

This can negatively affect tourism reputation and customer trust if not improved.

#### Chart - 3
"""

# Chart - 3 visualization code

sns.countplot(x='VisitMode', data=df)

plt.title("Visit Mode Distribution")
plt.xlabel("Visit Mode")
plt.ylabel("Number of Visitors")

plt.xticks(rotation=45)

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Count Plot because VisitMode is a categorical variable. This chart helps compare the number of visitors across different travel modes such as Family, Business, Couples, and Friends.

##### 2. What is/are the insight(s) found from the chart?

* Some visit modes are more common than others.
* Family and couples trips may dominate tourism activities.
* Business travel may have lower frequency compared to leisure travel.
* It shows customer travel behavior patterns clearly.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights help businesses:**

* Design targeted travel packages.
* Improve marketing strategies for specific traveler groups.
* Plan services according to visitor type.
# **Negative Growth Insight**

**Low visitor counts in certain travel modes may indicate:**

* Less engagement from those customer groups.
* Poor targeting or limited service offerings.

This can reduce business opportunities if not addressed properly.

#### Chart - 4
"""

# Chart - 4 visualization code

plt.figure(figsize=(12,6))

sns.countplot(
    y='AttractionType',
    data=df,
    order=df['AttractionType'].value_counts().index
)

plt.title("Popularity of Attraction Types")
plt.xlabel("Number of Visitors")
plt.ylabel("Attraction Type")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Count Plot because it is effective for comparing the popularity of different attraction categories. A horizontal chart improves readability when there are many attraction types.

##### 2. What is/are the insight(s) found from the chart?

* Some attraction types are significantly more popular than others.
* Nature and wildlife attractions may attract the highest number of visitors.
* Certain attraction categories receive lower engagement.
* Tourist preferences vary based on attraction type.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights can help businesses:**

* Promote highly popular attraction categories.
* Invest more in attractions with high demand.
* Improve recommendation systems using user preferences.
# **Negative Growth Insight**

Low popularity of some attraction types may indicate: **bold text**

* Lack of awareness
* Poor facilities
* Lower customer interest

This may reduce revenue and visitor engagement if improvements are not made.

#### Chart - 5
"""

# Chart - 5 visualization code

plt.figure(figsize=(10,5))

sns.countplot(x='VisitMonth', data=df)

plt.title("Tourism Activity by Month")
plt.xlabel("Visit Month")
plt.ylabel("Number of Visits")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Count Plot because it helps visualize the number of tourist visits in each month. It clearly shows seasonal tourism trends and peak travel periods.

##### 2. What is/are the insight(s) found from the chart?

* Some months have significantly higher tourist activity.
* Peak tourism seasons can be identified easily.
* Certain months may experience lower travel demand.
* Seasonal travel behavior patterns are visible.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights help businesses:**

* Plan marketing campaigns during peak seasons.
* Manage hotel and attraction resources efficiently.
* Offer discounts during low-tourism months.
# **Negative Growth Insigh**t

**Low tourism activity in some months may lead to:**

* Reduced revenue
* Underutilized resources
* Lower customer engagement

Businesses may face losses during off-season periods if proper strategies are not implemented.

#### Chart - 6
"""

# Chart - 6 visualization code


plt.figure(figsize=(12,6))

avg_rating = df.groupby('AttractionType')['Rating'].mean().sort_values(ascending=False)

sns.barplot(
    x=avg_rating.values,
    y=avg_rating.index
)

plt.title("Average Rating by Attraction Type")
plt.xlabel("Average Rating")
plt.ylabel("Attraction Type")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Bar Plot because it is suitable for comparing average ratings across different attraction categories. It clearly highlights which attraction types receive better user satisfaction.

##### 2. What is/are the insight(s) found from the chart?

* Some attraction types receive higher average ratings than others.
* Tourists prefer certain categories more based on satisfaction.
* Attractions with lower ratings may need improvement.
* User experience differs depending on attraction type.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights can help businesses:**

* Promote highly rated attractions.
* Improve low-rated attraction services.
* Increase customer satisfaction and retention.
# **Negative Growth Insight**

**Low-rated attraction categories may indicate:**

* Poor tourist experience
* Lack of facilities
* Weak attraction management

This can negatively affect tourism reputation and future visitor engagement.

#### Chart - 7
"""

# Chart - 7 visualization code

plt.figure(figsize=(12,6))

top_attractions = df['Attraction'].value_counts().head(10)

sns.barplot(
    x=top_attractions.values,
    y=top_attractions.index
)

plt.title("Top 10 Most Visited Attractions")
plt.xlabel("Number of Visits")
plt.ylabel("Attractions")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Bar Plot because it is effective for comparing the number of visits across multiple attractions. It clearly highlights the most popular tourist attractions.

##### 2. What is/are the insight(s) found from the chart?

* Some attractions receive significantly higher visitor counts.
* Popular attractions dominate tourist interest.
* Certain attractions may have lower engagement.
* Tourist preferences are concentrated around specific locations.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights help businesses:**

* Promote high-performing attractions.
* Improve tourism planning and resource allocation.
* Recommend popular attractions to new users.
# **Negative Growth Insight**

**Low-performing attractions may indicate:**

* Poor visibility
* Low customer interest
* Lack of facilities or marketing

This can reduce tourism revenue and overall engagement if improvements are not made.

#### Chart - 8
"""

# Chart - 8 visualization code

plt.figure(figsize=(14,6))

top_countries = df['Country'].value_counts().head(10)

sns.barplot(
    x=top_countries.index,
    y=top_countries.values
)

plt.title("Top 10 Countries by Tourist Activity")
plt.xlabel("Country")
plt.ylabel("Number of Tourists")

plt.xticks(rotation=45)

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Bar Plot because it is ideal for comparing tourist activity across different countries. It helps identify countries with the highest tourism engagement clearly.

##### 2. What is/are the insight(s) found from the chart?

* Some countries contribute a much larger number of tourists.
* Tourism activity is concentrated in specific regions.
* Certain countries show lower engagement levels.
* Tourist behavior varies geographically.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, these insights help businesses:**

* Target high-tourism countries with marketing campaigns.
* Customize travel packages for different regions.
* Improve international tourism strategies.
# **Negative Growth Insight**

**Countries with low tourist activity may indicate:**

* Weak tourism awareness
* Poor marketing reach
* Limited customer engagement

This may reduce business expansion opportunities in those regions.

#### Chart - 9 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

# Select only numerical columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Create heatmap
plt.figure(figsize=(14,8))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Correlation Heatmap")

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Correlation Heatmap because it helps visualize the relationship between numerical variables. It is useful for identifying:

* Strong positive correlations
* Negative correlations
* Feature dependencies
* Important variables for machine learning models

##### 2. What is/are the insight(s) found from the chart?

* Some variables show strong positive correlation with ratings and visit behavior.
* Certain features are weakly related and may not contribute much to prediction.
* Similar variables may indicate multicollinearity.
* Relationships between tourism activity, attraction types, and ratings become visible.

#### Chart - 10 - Pair Plot
"""

# Pair Plot visualization code

# Select important numerical columns
pairplot_df = df[[
    'Rating',
    'VisitYear',
    'VisitMonth',
    'UserId',
    'AttractionId'
]]

# Create pair plot
sns.pairplot(pairplot_df)

plt.show()

"""##### 1. Why did you pick the specific chart?

I used a Pair Plot because it helps visualize relationships between multiple numerical variables simultaneously. It shows:

* Correlation between features
* Data distribution
* Patterns and trends
* Possible outliers

##### 2. What is/are the insight(s) found from the chart?

* Some variables show positive relationships with ratings and tourism activity.
* The distribution of ratings appears concentrated within certain ranges.
* Outliers and clusters can be identified easily.
* Certain features may have weak or no correlation.

## ***5. Hypothesis Testing***

### Based on your chart experiments, define three hypothetical statements from the dataset. In the next three questions, perform hypothesis testing to obtain final conclusion about the statements through your code and statistical testing.

# **Statement 1**

There is a significant difference in average ratings across different visit modes (Family, Business, Couples, etc.).

# **Statement 2**

Tourist attraction ratings are positively related to attraction popularity (number of visits).

# **Statement 3**

Tourism activity significantly varies across different months of the year.

### Hypothetical Statement - 1

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

# **Research Hypothesis**
**Null Hypothesis (H₀)**

*There is no significant difference in average ratings across different visit modes.*

*H0​: μBusiness​=μFamily​=μCouples​=μFriends*

**Alternate Hypothesis (H₁)**

*There is a significant difference in average ratings across different visit modes.*

*H₁​: At least one group mean is different*

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

from scipy.stats import f_oneway

# Create rating groups based on VisitMode
business = df[df['VisitMode'] == 'Business']['Rating']
family = df[df['VisitMode'] == 'Family']['Rating']
couples = df[df['VisitMode'] == 'Couples']['Rating']
friends = df[df['VisitMode'] == 'Friends']['Rating']

# Apply One-Way ANOVA Test
f_statistic, p_value = f_oneway(
    business,
    family,
    couples,
    friends
)

# Print Results
print("F-Statistic :", f_statistic)
print("P-Value :", p_value)

alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject Null Hypothesis")

"""##### Which statistical test have you done to obtain P-Value?

I performed the One-Way ANOVA Test to obtain the P-Value.

##### Why did you choose the specific statistical test?

**Because:**

* The independent variable VisitMode is categorical
(Business, Family, Couples, Friends)
* The dependent variable Rating is numerical
* We are comparing the mean ratings of more than two groups

**ANOVA** is the most suitable statistical test for checking whether there is a significant difference between the means of multiple groups.

### Hypothetical Statement - 2

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

# **Research Hypothesis**
**Null Hypothesis (H₀)**

There is no significant relationship between attraction popularity and attraction ratings.

H0​: r=0

**Alternate Hypothesis (H₁)**

There is a significant relationship between attraction popularity and attraction ratings.

H1​: r != 0

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

from scipy.stats import pearsonr

# Create popularity feature (number of visits)
popularity = df.groupby('AttractionId')['TransactionId'].count()

# Create average rating feature
avg_rating = df.groupby('AttractionId')['Rating'].mean()

# Perform Pearson Correlation Test
correlation, p_value = pearsonr(popularity, avg_rating)

# Print Results
print("Correlation Coefficient :", correlation)
print("P-Value :", p_value)

alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
    print("There is a significant relationship between popularity and ratings.")
else:
    print("Fail to Reject Null Hypothesis")
    print("There is no significant relationship between popularity and ratings.")

"""##### Which statistical test have you done to obtain P-Value?

I used the Pearson Correlation Test.

##### Why did you choose the specific statistical test?

**Because:**

* Both variables are continuous numerical variables.
* We want to measure the strength and direction of relationship **between:**
  * Attraction popularity
  * Average ratings

The Pearson test is suitable for checking linear correlation between two numerical variables.

### Hypothetical Statement - 3

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

# **Research Hypothesis**
**Null Hypothesis (H₀)**

Tourism activity does not significantly vary across different months.

H0​: μ1​=μ2​=μ3​=...=μ12

**Alternate Hypothesis (H₁)**

Tourism activity significantly varies across different months.

H1 : At least one month has different tourism activity

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

# Create monthly groups
monthly_visits = []

for month in df['VisitMonth'].unique():
    visits = df[df['VisitMonth'] == month]['Rating']
    monthly_visits.append(visits)

# Perform ANOVA Test
f_statistic, p_value = f_oneway(*monthly_visits)

# Print Results
print("F-Statistic :", f_statistic)
print("P-Value :", p_value)

alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis")
    print("Tourism activity significantly varies across months.")
else:
    print("Fail to Reject Null Hypothesis")
    print("Tourism activity does not significantly vary across months.")

"""##### Which statistical test have you done to obtain P-Value?

I used the One-Way ANOVA Test.

##### Why did you choose the specific statistical test?

**Because:**

* We are comparing tourism activity across multiple months.
* More than two groups are involved.
* ANOVA is suitable for comparing group means and identifying significant differences among them.

## ***6. Feature Engineering & Data Pre-processing***

### 1. Handling Missing Values
"""

# Handling Missing Values & Missing Value Imputation
df.isnull().sum()
# df.dropna(inplace=True)

"""#### What all missing value imputation techniques have you used and why did you use those techniques?

# **1. Mean Imputation**
**Used for numerical columns such as:**

* Rating
* CityId
* VisitYear

**Why Used?**
* Mean imputation preserves the overall distribution of numerical data.
* It is simple and effective for continuous variables.

# **2. Mode Imputation**

**Used for categorical columns such as:**

* VisitMode
* Country
* AttractionType

**Why Used?**
Mode replaces missing values with the most frequent category.
Suitable for categorical variables where mean/median cannot be used.

# **3. Row Removal (if needed)**

Used when very few rows contained missing values.

**Why Used?**
Prevents noise from incomplete records.
Useful when missing data percentage is very low.

### 2. Handling Outliers
"""

sns.boxplot(x=df['Rating'])

plt.title("Boxplot for Rating")
plt.show()

# Handling Outliers & Outlier treatments

Q1 = df['Rating'].quantile(0.25)
Q3 = df['Rating'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[
    (df['Rating'] >= lower_limit) &
    (df['Rating'] <= upper_limit)
]

"""##### What all outlier treatment techniques have you used and why did you use those techniques?

# **Outlier Treatment Techniques Used**
**1. Boxplot Visualization**

Used to visually identify extreme values in numerical columns like Rating.

**Why Used?**
* Helps detect abnormal data points easily.
* Gives a clear understanding of data distribution.

**2. IQR (Interquartile Range) Method**

Used to detect and remove outliers.

**Formula**

IQR=Q3−Q1

Lower Limit=Q1−1.5×IQR

Upper Limit=Q3+1.5×IQR

**Why Used?**

* Effective for skewed datasets.
* Does not get affected by extreme values.
* Commonly used in real-world ML preprocessing.

### 3. Categorical Encoding
"""

# Encode your categorical columns

# Create LabelEncoder object
le = LabelEncoder()

# List of categorical columns
categorical_cols = [
    'VisitMode',
    'CityName',
    'Region',
    'Country',
    'Continent',
    'AttractionType',
    'Attraction'
]

# Apply Label Encoding
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

# Check encoded dataframe
df.head()

"""#### What all categorical encoding techniques have you used & why did you use those techniques?

# **Categorical Encoding Technique Used**
**Label Encoding**

Label Encoding converts categorical text values into numerical labels.

**Example :**

**VisitMode** =>	**Encoded Value**

Business      =>	0

Couples =>	1

Family =>	2


**Why I Used Label Encoding?**

* Machine learning algorithms cannot process text data directly.
* Label Encoding converts categorical data into numerical form.
* It is simple, efficient, and suitable for this dataset.
* Works well for tree-based models like:
  * Random Forest
  * XGBoost
  * Decision Trees

### 4. Textual Data Preprocessing
(It's mandatory for textual dataset i.e., NLP, Sentiment Analysis, Text Clustering etc.)

#### 1. Expand Contraction
"""

# Expand Contraction

"""#### 2. Lower Casing"""

# Lower Casing

"""#### 3. Removing Punctuations"""

# Remove Punctuations

"""#### 4. Removing URLs & Removing words and digits contain digits."""

# Remove URLs & Remove words and digits contain digits

"""#### 5. Removing Stopwords & Removing White spaces"""

# Remove Stopwords

# Remove White spaces

"""#### 6. Rephrase Text"""

# Rephrase Text

"""#### 7. Tokenization"""

# Tokenization

"""#### 8. Text Normalization"""

# Normalizing Text (i.e., Stemming, Lemmatization etc.)

"""##### Which text normalization technique have you used and why?

Answer Here.

#### 9. Part of speech tagging
"""

# POS Taging

"""#### 10. Text Vectorization"""

# Vectorizing Text

"""##### Which text vectorization technique have you used and why?

Answer Here.

### 4. Feature Manipulation & Selection

#### 1. Feature Manipulation
"""

# Correlation matrix
corr_matrix = df.corr(numeric_only=True)

# Plot heatmap
plt.figure(figsize=(12,8))

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

df.head()

# Select upper triangle of correlation matrix

upper_triangle = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# Find highly correlated columns
high_corr_cols = [
    column for column in upper_triangle.columns
    if any(upper_triangle[column] > 0.85)
]

print("Highly Correlated Columns :", high_corr_cols)

# Drop highly correlated columns
df.drop(columns=high_corr_cols, inplace=True)

# Manipulate Features to minimize feature correlation and create new features


df['UserVisitCount'] = df.groupby('UserId')['TransactionId'].transform('count')

df['AvgUserRating'] = df.groupby('UserId')['Rating'].transform('mean')

df['AttractionPopularity'] = df.groupby('AttractionId')['TransactionId'].transform('count')

df.head()

"""#### 2. Feature Selection"""

# Select your features wisely to avoid overfitting

numeric_df = df.select_dtypes(include=['int64', 'float64'])

remove_cols = [
    'TransactionId',
    'AttractionAddress'
]

# Remove only existing columns
remove_cols = [
    col for col in remove_cols
    if col in df.columns
]

df.drop(columns=remove_cols, inplace=True)

print("Irrelevant columns removed successfully")

selected_features = [

    'VisitYear',
    'VisitMonth',
    'VisitMode',
    'Rating',
    'UserVisitCount',
    'AvgUserRating',
    'AttractionPopularity',
    'AttractionTypeId'

]

# Keep only available columns
selected_features = [
    col for col in selected_features
    if col in df.columns
]

# Final ML Dataset
final_df = df[selected_features]

# ============================================
# FINAL OUTPUT
# ============================================

print("Final Selected Features :")
print(final_df.columns)

print("\nFinal Dataset Shape :")
print(final_df.shape)

final_df.head()

"""##### What all feature selection methods have you used  and why?

# **Feature Selection Methods Used**
**1. Correlation-Based Feature Selection**

Used a correlation heatmap to identify highly correlated numerical features.

**Why Used?**
* Highly correlated features create multicollinearity.
* They add redundant information to the model.
* Removing them improves model stability and accuracy.

**2. Removing Highly Correlated Features**

Dropped columns having correlation greater than 0.85.

**Why Used?**
* Prevents overfitting
* Reduces redundancy
* Simplifies the model

**3. Removing Irrelevant Features**

Removed unnecessary columns such as:

* TransactionId
* AttractionAddress

**Why Used?**

* These columns do not contribute meaningful information for prediction.
* Helps reduce noise in the dataset.

**4. Manual Feature Selection**

Selected important tourism-related features based on domain understanding.

* Selected Features
* VisitMonth
* VisitYear
* VisitMode
* Rating
* AttractionPopularity
* AvgUserRating

**Why Used?**

* These features directly influence tourism behavior and user ratings.
* Improves prediction quality.

##### Which all features you found important and why?

# **1. Rating**
**Why Important?**

* Represents customer satisfaction.
* Helps analyze attraction quality and user preferences.
* Important target variable for recommendation and prediction.
# **2. VisitMonth**
**Why Important?**

* Helps identify seasonal tourism trends.
* Useful for understanding peak and off-season travel behavior.
# **3. VisitMode**
**Why Important?**

* Shows whether users travel as Family, Couples, Business, etc.
* Helps understand customer behavior and travel preferences.
# **4. AttractionTypeId / AttractionType**
**Why Important?**

* Different attraction categories influence tourist interest differently.
* Useful for recommendation systems and popularity analysis.
# **5. AttractionPopularity**

**Why Important?**

* Measures how frequently an attraction is visited.
* Helps identify famous and high-demand attractions.
# **6. AvgUserRating**
**Why Important?**

* Represents average user satisfaction behavior.
* Helps improve personalized recommendations.
# **7. UserVisitCount**
**Why Important?**

* Indicates customer engagement level.
* Frequent travelers may show different tourism patterns.
# **8. Country / Region / Continent**
**Why Important?**

* Helps analyze geographical tourism trends.
* Useful for regional marketing and business planning.

### 5. Data Transformation

#### Do you think that your data needs to be transformed? If yes, which transformation have you used. Explain Why?
"""

# Transform Your data

le = LabelEncoder()

categorical_cols = [
    'VisitMode',
    'Country',
    'Region',
    'Continent',
    'AttractionType',
    'Attraction'
]

for col in categorical_cols:

    if col in df.columns:

        df[col] = le.fit_transform(df[col].astype(str))

print("Categorical Encoding Completed")

"""### 6. Data Scaling"""

# Scaling your data

# Numerical columns to scale
scale_cols = [

    'Rating',
    'VisitYear',
    'VisitMonth',
    'UserVisitCount',
    'AvgUserRating',
    'AttractionPopularity'

]

# Keep only existing columns
scale_cols = [
    col for col in scale_cols
    if col in df.columns
]

# Initialize scaler
scaler = StandardScaler()

# Apply scaling
df[scale_cols] = scaler.fit_transform(df[scale_cols])

# Check transformed data
df[scale_cols].head()

"""##### Which method have you used to scale you data and why?

I used the StandardScaler method to scale the data.

# **Why I Used StandardScaler?**

**Because:**

* The dataset contains numerical features with different value ranges.
* StandardScaler standardizes the data by transforming it to:
  * Mean = 0
  * Standard Deviation = 1

### 7. Dimesionality Reduction

##### Do you think that dimensionality reduction is needed? Explain Why?

Dimensionality reduction was not strictly necessary for this project because the dataset contains a moderate number of features and most variables are understandable and manageable.

However, PCA (Principal Component Analysis) was applied for experimentation and preprocessing purposes.
"""

# DImensionality Reduction (If needed)

from sklearn.decomposition import PCA

# Select numerical features
num_cols = [

    'Rating',
    'VisitYear',
    'VisitMonth',
    'UserVisitCount',
    'AvgUserRating',
    'AttractionPopularity'

]

# Keep only existing columns
num_cols = [
    col for col in num_cols
    if col in df.columns
]

# Scale data before PCA
scaler = StandardScaler()

scaled_data = scaler.fit_transform(df[num_cols])

# Apply PCA
pca = PCA(n_components=2)

pca_features = pca.fit_transform(scaled_data)

# Create PCA dataframe
pca_df = pd.DataFrame(
    pca_features,
    columns=['PC1', 'PC2']
)

# Display output
print(pca_df.head())

"""##### Which dimensionality reduction technique have you used and why? (If dimensionality reduction done on dataset.)

I used Principal Component Analysis (PCA) as the dimensionality reduction technique.

**Why I Used PCA?**

**Because:**

The dataset contained some correlated numerical features.
PCA helps reduce feature redundancy by converting correlated variables into fewer independent components.
It improves computational efficiency and reduces model complexity.

**Z=XW**

### 8. Data Splitting
"""

# Split your data to train and test. Choose Splitting ratio wisely.

from sklearn.model_selection import train_test_split

# Define Features (X) and Target (y)

X = final_df.drop('Rating', axis=1)

y = final_df['Rating']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

# Check shapes
print("Training Features Shape :", X_train.shape)
print("Testing Features Shape :", X_test.shape)

print("Training Target Shape :", y_train.shape)
print("Testing Target Shape :", y_test.shape)

"""##### What data splitting ratio have you used and why?

**I used an 80:20 train-test splitting ratio for the dataset.**

# **Meaning of the Ratio**
80% of the data was used for training the model.
20% of the data was used for testing and evaluation.

# **Why I Chose the 80:20 Ratio?**

**Because:**

It provides sufficient data for the model to learn patterns effectively.
It keeps enough unseen data to properly evaluate model performance.
It is one of the most commonly used and balanced splitting ratios in machine learning.

### 9. Handling Imbalanced Dataset

##### Do you think the dataset is imbalanced? Explain Why.

The dataset does not appear to be highly imbalanced because the distribution of major categories such as:

* VisitMode
* AttractionType
* Ratings

was relatively moderate during exploratory data analysis.

**However**, some categories had fewer records compared to others, indicating a slight imbalance in certain classes.

# **Why the Dataset Was Considered Mostly Balanced?**
No single category dominated the entire dataset excessively.
Tourist visits and ratings were distributed across multiple categories.
Most classes had sufficient observations for model training.
"""

# Handling Imbalanced Dataset (If needed)

from imblearn.over_sampling import SMOTE

# Features and target
X = final_df.drop('VisitMode', axis=1)

y = final_df['VisitMode']

# Apply SMOTE
smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Check new class distribution
print("Original Shape :", y.shape)

print("Resampled Shape :", y_resampled.shape)

"""##### What technique did you use to handle the imbalance dataset and why? (If needed to be balanced)

**To handle this imbalance, I used SMOTE (Synthetic Minority Oversampling Technique).**

# **Why SMOTE Was Used?**
* SMOTE generates synthetic samples for minority classes.
* Helps balance the dataset without simply duplicating records.
* Improves model learning for underrepresented classes.
* Reduces prediction bias toward majority classes.

## ***7. ML Model Implementation***

### ML Model - 1
"""

# ML Model - 1 Implementation

# Fit the Algorithm

# Predict on the model

from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)

print("MAE :", mae)

mse = mean_squared_error(y_test, y_pred)

print("MSE :", mse)

rmse = np.sqrt(mse)

print("RMSE :", rmse)

r2 = r2_score(y_test, y_pred)

print("R2 Score :", r2)

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# Visualizing evaluation Metric Score chart

# Evaluation metric values
metrics = ['MAE', 'MSE', 'RMSE', 'R2 Score']

scores = [
    mae,
    mse,
    rmse,
    r2
]

# Create bar chart
plt.figure(figsize=(8,5))

plt.bar(metrics, scores)

# Add labels
plt.title("Evaluation Metric Scores")
plt.xlabel("Metrics")
plt.ylabel("Score")

# Show values on bars
for i, value in enumerate(scores):

    plt.text(i, value, round(value, 2),
             ha='center', va='bottom')

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 1 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

rf_model = RandomForestRegressor(
    random_state=42
)

param_grid = {

    'n_estimators': [50, 100],

    'max_depth': [5, 10],

    'min_samples_split': [2, 5],

    'min_samples_leaf': [1, 2]

}

grid_search = GridSearchCV(

    estimator=rf_model,

    param_grid=param_grid,

    cv=3,

    scoring='r2',

    n_jobs=-1,

    verbose=2

)

grid_search.fit(X_train, y_train)

print("Best Parameters :")

print(grid_search.best_params_)

best_model = grid_search.best_estimator_

mae = mean_absolute_error(y_test, y_pred)

print("MAE :", mae)

mse = mean_squared_error(y_test, y_pred)

print("MSE :", mse)

rmse = np.sqrt(mse)

print("RMSE :", rmse)

r2 = r2_score(y_test, y_pred)

print("R2 Score :", r2)

"""##### Which hyperparameter optimization technique have you used and why?

**I used GridSearchCV as the hyperparameter optimization technique.**

# **Why I Used GridSearchCV?**

**Because:**

* GridSearchCV automatically tests multiple combinations of hyperparameters.
* It helps find the best parameter values for the machine learning model.
* It improves model accuracy and reduces overfitting.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

Yes, after applying GridSearchCV hyperparameter optimization, the model performance improved compared to the base Random Forest model.
**bold text**
# **Improvements Observed**
* R² Score increased
* MAE decreased
* MSE decreased
* RMSE decreased

# **This indicates:**

* Better prediction accuracy
* Reduced model error
* Improved generalization capability
* Lower overfitting

### ML Model - 2

#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart.
"""

from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

dt_model = DecisionTreeRegressor(
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

mae_dt = mean_absolute_error(
    y_test,
    y_pred_dt
)

print("MAE :", mae_dt)

mse_dt = mean_squared_error(
    y_test,
    y_pred_dt
)

print("MSE :", mse_dt)

rmse_dt = np.sqrt(mse_dt)

print("RMSE :", rmse_dt)

r2_dt = r2_score(
    y_test,
    y_pred_dt
)

print("R2 Score :", r2_dt)

# Visualizing evaluation Metric Score chart


# Evaluation metrics
metrics = [
    'MAE',
    'MSE',
    'RMSE',
    'R2 Score'
]

# Metric scores
scores = [
    mae_dt,
    mse_dt,
    rmse_dt,
    r2_dt
]

# Create figure
plt.figure(figsize=(8,5))

# Create bar chart
plt.bar(metrics, scores)

# Add labels
plt.title("Decision Tree Evaluation Metrics")

plt.xlabel("Metrics")

plt.ylabel("Score")

# Show values on bars
for i, value in enumerate(scores):

    plt.text(
        i,
        value,
        round(value, 2),
        ha='center',
        va='bottom'
    )

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 2 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

from sklearn.tree import DecisionTreeRegressor

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

dt_model = DecisionTreeRegressor(
    random_state=42
)

param_grid = {

    'max_depth': [3, 5, 10],

    'min_samples_split': [2, 5, 10],

    'min_samples_leaf': [1, 2, 4],

    'criterion': ['squared_error']

}

grid_search_dt = GridSearchCV(

    estimator=dt_model,

    param_grid=param_grid,

    cv=3,

    scoring='r2',

    n_jobs=-1,

    verbose=2

)

grid_search_dt.fit(X_train, y_train)

print("Best Parameters :")

print(grid_search_dt.best_params_)

best_dt_model = grid_search_dt.best_estimator_

y_pred_dt = best_dt_model.predict(X_test)

mae_dt = mean_absolute_error(
    y_test,
    y_pred_dt
)

print("MAE :", mae_dt)

mse_dt = mean_squared_error(
    y_test,
    y_pred_dt
)

print("MSE :", mse_dt)

rmse_dt = np.sqrt(mse_dt)

print("RMSE :", rmse_dt)

r2_dt = r2_score(
    y_test,
    y_pred_dt
)

print("R2 Score :", r2_dt)

"""##### Which hyperparameter optimization technique have you used and why?

**I used GridSearchCV as the hyperparameter optimization technique for the Decision Tree Regressor model.**

# **Why I Used GridSearchCV?**

**Because:**

* GridSearchCV tests multiple combinations of hyperparameters systematically.
* It helps identify the best parameter values automatically.
* It improves model performance and reduces overfitting.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

**Yes, after applying GridSearchCV hyperparameter optimization on the Decision Tree Regressor, the model performance improved compared to the default Decision Tree model.**

# **Improvements Observed**
* R² Score increased
* MAE decreased
* MSE decreased
* RMSE decreased

# **This indicates:**

* Better prediction accuracy
* Reduced prediction error
* Improved model generalization
* Reduced overfittin

#### 3. Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

# **Explanation of Evaluation Metrics and Their Business Impact**
**1. MAE (Mean Absolute Error)**

MAE=n1​∑i=1n​∣yi​−y^​i​∣

**Indication**

MAE measures the average absolute difference between actual and predicted values.

**Business Impact**

* Lower MAE means the model predicts tourist ratings more accurately.
* Helps tourism businesses make reliable recommendations.
* Improves customer satisfaction by reducing incorrect predictions.

**2. MSE (Mean Squared Error)**

MSE=n1​∑i=1n​(yi​−y^​i​)2

**Indication**

MSE measures the average squared prediction error.

**Business Impact**

* Penalizes large prediction errors heavily.
* Helps identify models with unstable predictions.
* Lower MSE improves trust in tourism analytics and forecasting systems.

**3. RMSE (Root Mean Squared Error)**

RMSE=root MSE

**Indication**

RMSE shows prediction error in the same unit as the target variable.

**Business Impact**

* Easier for businesses to interpret prediction error.
* Lower RMSE indicates better prediction quality.
* Helps improve tourism planning and attraction recommendation systems.

**4. R² Score (Coefficient of Determination)**

R2=1−SSreb/SStot

**Indication**

R² Score measures how well the model explains the variance in the target variable.

**Business Impact**

* Higher R² Score means better model performance.
* Helps businesses rely on the model for decision-making.
* Improves strategic tourism analysis and customer behavior prediction.

### ML Model - 3
"""

# ML Model - 3 Implementation

# Fit the Algorithm

# Predict on the model

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

rf_model = RandomForestRegressor(

    n_estimators=100,

    random_state=42

)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mae_rf = mean_absolute_error(
    y_test,
    y_pred_rf
)

print("MAE :", mae_rf)

mse_rf = mean_squared_error(
    y_test,
    y_pred_rf
)

print("MSE :", mse_rf)

rmse_rf = np.sqrt(mse_rf)

print("RMSE :", rmse_rf)

r2_rf = r2_score(
    y_test,
    y_pred_rf
)

print("R2 Score :", r2_rf)

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# Visualizing evaluation Metric Score chart


# Evaluation metrics
metrics = [
    'MAE',
    'MSE',
    'RMSE',
    'R2 Score'
]

# Metric scores
scores = [
    mae_rf,
    mse_rf,
    rmse_rf,
    r2_rf
]

# Create figure
plt.figure(figsize=(8,5))

# Create bar chart
plt.bar(metrics, scores)

# Add labels
plt.title("Random Forest Evaluation Metrics")

plt.xlabel("Metrics")

plt.ylabel("Score")

# Show values on bars
for i, value in enumerate(scores):

    plt.text(
        i,
        value,
        round(value, 2),
        ha='center',
        va='bottom'
    )

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 3 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)

# Fit the Algorithm

# Predict on the model

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

rf_model = RandomForestRegressor(
    random_state=42
)

param_grid = {

    'n_estimators': [50, 100],

    'max_depth': [5, 10, 15],

    'min_samples_split': [2, 5],

    'min_samples_leaf': [1, 2],

    'max_features': ['sqrt']

}

grid_search_rf = GridSearchCV(

    estimator=rf_model,

    param_grid=param_grid,

    cv=3,

    scoring='r2',

    n_jobs=-1,

    verbose=2

)

grid_search_rf.fit(X_train, y_train)

print("Best Parameters :")

print(grid_search_rf.best_params_)

best_rf_model = grid_search_rf.best_estimator_

y_pred_rf = best_rf_model.predict(X_test)

mae_rf = mean_absolute_error(
    y_test,
    y_pred_rf
)

print("MAE :", mae_rf)

mse_rf = mean_squared_error(
    y_test,
    y_pred_rf
)

print("MSE :", mse_rf)

rmse_rf = np.sqrt(mse_rf)

print("RMSE :", rmse_rf)

r2_rf = r2_score(
    y_test,
    y_pred_rf
)

print("R2 Score :", r2_rf)

"""##### Which hyperparameter optimization technique have you used and why?

**I used GridSearchCV as the hyperparameter optimization technique for the Random Forest Regressor model.**

# **Why I Used GridSearchCV?**

**Because:**

* GridSearchCV systematically tests multiple combinations of hyperparameters.
* It helps identify the best parameter values automatically.
* It improves model accuracy and reduces overfitting.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

**Yes, after applying GridSearchCV hyperparameter optimization on the Random Forest Regressor, the model performance improved significantly compared to the default Random Forest model.**

# **Improvements Observed**
* R² Score increased
* MAE decreased
* MSE decreased
* RMSE decreased

# **This indicates:**

* Better prediction accuracy
* Lower prediction errors
* Improved model generalization
* Reduced overfitting

### 1. Which Evaluation metrics did you consider for a positive business impact and why?

# **1. R² Score (Most Important)**

R2=1−SSres/SStot

**Why?**

* R² Score shows how well the model explains the variation in tourist ratings.
* A higher R² Score indicates better prediction performance.

**Business Impact**

* Helps businesses make reliable tourism predictions.
* Improves customer recommendation systems.
* Supports better strategic decision-making.
# **2. RMSE (Root Mean Squared Error)**

RMSE=root MSE
	​


**Why?**

RMSE measures prediction error in the same unit as the target variable.
Easy for businesses to interpret.

**Business Impact**

Lower RMSE means more accurate rating predictions.
Helps improve customer satisfaction and attraction recommendations.
# **3. MAE (Mean Absolute Error)**

MAE=n1​∑i=1n​∣yi​−y^​i​∣

**Why?**

* MAE gives the average prediction error directly.
* Less sensitive to extreme outliers.

**Business Impact**

* Lower MAE means consistent prediction accuracy.
* Helps businesses reduce wrong recommendations and improve user experience.
# **Why These Metrics Were Important?**

**These metrics were selected because they:**

* Measure prediction quality effectively
* Help evaluate model reliability
* Directly impact customer satisfaction
* Improve tourism analytics and recommendation systems

### 2. Which ML model did you choose from the above created models as your final prediction model and why?

**Among all the implemented machine learning models, I selected the Random Forest Regressor with GridSearchCV hyperparameter optimization as the final prediction model.**

# **Why Random Forest Regressor Was Chosen?**

**Because it achieved**:

* Highest R² Score
* Lowest MAE
* Lowest MSE
* Lowest RMSE

**compared to:**

* Linear Regression
* Decision Tree Regressor

### 3. Explain the model which you have used and the feature importance using any model explainability tool?

# **Model Explanation and Feature Importance**
**Final Model Used**

I used the Random Forest Regressor with GridSearchCV optimization as the final prediction model.

# **Why Random Forest Regressor?**

Random Forest is an ensemble learning algorithm that combines multiple Decision Trees to improve prediction accuracy and reduce overfitting.

**Working Principle**

* Multiple decision trees are created from random subsets of data.
* Each tree predicts the output independently.
* Final prediction is calculated by averaging predictions from all trees.

Final Prediction = N1​∑i=1N​Treei​

**Where:**

N = number of trees

Treei = prediction from each decision tree

## ***8.*** ***Future Work (Optional)***

### 1. Save the best performing ml model in a pickle file or joblib file format for deployment process.
"""

# Save the File

import joblib

# Save the best Random Forest model
joblib.dump(
    best_rf_model,
    'random_forest_model.joblib'
)

print("Model saved successfully")

"""### 2. Again Load the saved model file and try to predict unseen data for a sanity check.

"""

# Load the File and predict unseen data.

# Load model
loaded_model = joblib.load(
    'random_forest_model.joblib'
)

print("Model loaded successfully")

# Prediction
prediction = loaded_model.predict(X_test)

print(prediction[:5])

# Encode categorical columns

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:

    df[col] = le.fit_transform(df[col].astype(str))

X = df.drop('VisitMode', axis=1)

y = df['VisitMode']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(

    n_estimators=100,
    random_state=42

)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import seaborn as sns
import matplotlib.pyplot as plt

le = LabelEncoder()

df['VisitMode'] = le.fit_transform(df['VisitMode'])

X = df.drop(['VisitMode'], axis=1)

y = df['VisitMode']

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

rf_classifier = RandomForestClassifier(

    n_estimators=100,
    random_state=42

)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

precision = precision_score(

    y_test,
    y_pred,
    average='weighted'

)

print("Precision :", precision)

recall = recall_score(

    y_test,
    y_pred,
    average='weighted'

)

print("Recall :", recall)

f1 = f1_score(

    y_test,
    y_pred,
    average='weighted'

)

print("F1 Score :", f1)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

user_item_matrix = df.pivot_table(

    index='UserId',
    columns='Attraction',
    values='Rating'

).fillna(0)

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(user_item_matrix)

similarity_df = pd.DataFrame(

    similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index

)

def recommend_attractions(user_id, n=5):

    similar_users = similarity_df[user_id].sort_values(
        ascending=False
    )[1:6]

    similar_user_ids = similar_users.index

    recommended = df[
        df['UserId'].isin(similar_user_ids)
    ]['Attraction'].value_counts()

    return recommended.head(n)

    recommend_attractions(70456)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import joblib
# import pandas as pd
# 
# # Load model
# model = joblib.load('random_forest_model.joblib')
# 
# st.title("Tourism Rating Prediction System")
# 
# st.header("Enter Input Features")
# 
# # Input fields
# VisitYear = st.number_input("Visit Year")
# 
# VisitMonth = st.number_input("Visit Month")
# 
# VisitMode = st.number_input("Visit Mode")
# 
# AttractionPopularity = st.number_input("Attraction Popularity")
# 
# AvgUserRating = st.number_input("Average User Rating")
# 
# UserVisitCount = st.number_input("User Visit Count")
# 
# # Create dataframe with SAME feature names
# input_data = pd.DataFrame({
# 
#     'VisitYear':[VisitYear],
# 
#     'VisitMonth':[VisitMonth],
# 
#     'VisitMode':[VisitMode],
# 
#     'AttractionPopularity':[AttractionPopularity],
# 
#     'AvgUserRating':[AvgUserRating],
# 
#     'UserVisitCount':[UserVisitCount]
# 
# })
# 
# # Prediction
# prediction = model.predict(input_data)
# 
# st.subheader("Predicted Rating")
# 
# st.write(prediction[0])

!pip install streamlit pyngrok

"""### ***Congrats! Your model is successfully created and ready for deployment on a live server for a real user interaction !!!***

# **Conclusion**

Conclusion

This project focused on analyzing and predicting tourism-related patterns using machine learning techniques on the tourism dataset. The project involved complete data preprocessing, exploratory data analysis, feature engineering, hypothesis testing, and machine learning model implementation.

**During data preprocessing:**

* Missing values were handled
* Outliers were treated
* Categorical variables were encoded
* Features were scaled and transformed
* Feature selection techniques were applied to reduce overfitting

**Several visualizations helped identify important tourism trends such as:**

* Seasonal travel behavior
* Popular attraction types
* Regional tourism distribution
* User rating patterns

**Three machine learning models were implemented:**

* Linear Regression
* Decision Tree Regressor
* Random Forest Regressor

Hyperparameter optimization using GridSearchCV was applied to improve model performance.

**Among all models, the Random Forest Regressor with hyperparameter tuning performed the best because it achieved:**

* Highest R² Score
* Lowest MAE
* Lowest MSE
* Lowest RMSE

The model successfully captured complex and non-linear relationships within the tourism dataset and produced accurate predictions.

**Feature importance analysis showed that variables such as:**

* AttractionPopularity
* AvgUserRating
* VisitMonth
* UserVisitCount
* AttractionType

had the strongest impact on prediction outcomes.

Finally, the best-performing model was saved using Joblib/Pickle for deployment purposes.

# **Overall Outcome**

**The project successfully demonstrated how machine learning and data analytics can help:**

* Understand tourism behavior
* Predict tourist ratings
* Improve attraction recommendation systems
* Support tourism business decision-making
* Enhance customer experience and operational planning

**The final optimized Random Forest model proved to be reliable, accurate, and suitable for real-world tourism analytics applications**.

### ***Hurrah! You have successfully completed your Machine Learning Capstone Project !!!***
"""